version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      web-production:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      web-development:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      web-major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: pub
    directory: /mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      mobile-production:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      mobile-development:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      mobile-major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      docker-base-images:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      docker-base-images-major:
        patterns:
          - "*"
        update-types:
          - major
